type settings_limit_ret = { __bottom__: nil }
type trees_controller_add_one_ret = untyped
type trees_controller_bump_ret = untyped
type trees_controller_limit_text_ret = { __bottom__: nil }
type trees_controller_ping_ret = untyped
type trees_controller_pong_ret = untyped
type trees_controller_render_label_ret = untyped
type trees_controller_settings_limit_ret = { __bottom__: nil }
type trees_controller_shout_ret = untyped
type trees_controller_triple_ret = untyped
type trees_controller_twice_ret = untyped
