type trees_controller_even_count_ret = untyped
type trees_controller_odd_count_ret = untyped
type trees_controller_walk_tree_ret = Array[untyped]
type walker_scale_ret = { __bottom__: nil }
type walker_walk_ret = Array[walker_walk_ret]
