fn kind(e:&Expr)->&'static str {
    match &*e.node {
        ExprNode::Lit { .. } => "Lit",
        ExprNode::Var { .. } => "Var",
        ExprNode::Ivar { .. } => "Ivar",
        ExprNode::Const { .. } => "Const",
        ExprNode::Hash { .. } => "Hash",
        ExprNode::Array { .. } => "Array",
        ExprNode::StringInterp { .. } => "StringInterp",
        ExprNode::BoolOp { .. } => "BoolOp",
        ExprNode::Let { .. } => "Let",
        ExprNode::Lambda { .. } => "Lambda",
        ExprNode::MethodRef { .. } => "MethodRef",
        ExprNode::Apply { .. } => "Apply",
        ExprNode::Send { .. } => "Send",
        ExprNode::If { .. } => "If",
        ExprNode::Case { .. } => "Case",
        ExprNode::CaseMatch { .. } => "CaseMatch",
        ExprNode::MatchPredicate { .. } => "MatchPredicate",
        ExprNode::MatchRequired { .. } => "MatchRequired",
        ExprNode::Seq { .. } => "Seq",
        ExprNode::Assign { .. } => "Assign",
        ExprNode::OpAssign { .. } => "OpAssign",
        ExprNode::Yield { .. } => "Yield",
        ExprNode::Raise { .. } => "Raise",
        ExprNode::RescueModifier { .. } => "RescueModifier",
        ExprNode::SelfRef => "SelfRef",
        ExprNode::Return { .. } => "Return",
        ExprNode::Super { .. } => "Super",
        ExprNode::Next { .. } => "Next",
        ExprNode::Break { .. } => "Break",
        ExprNode::Retry => "Retry",
        ExprNode::Redo => "Redo",
        ExprNode::Splat { .. } => "Splat",
        ExprNode::ForwardArgs => "ForwardArgs",
        ExprNode::ForwardKeywords => "ForwardKeywords",
        ExprNode::Defined { .. } => "Defined",
        ExprNode::KeywordSplat { .. } => "KeywordSplat",
        ExprNode::MultiAssign { .. } => "MultiAssign",
        ExprNode::While { .. } => "While",
        ExprNode::Range { .. } => "Range",
        ExprNode::BeginRescue { .. } => "BeginRescue",
        ExprNode::Cast { .. } => "Cast",
    }
}
