type base_doubled_ret = { __bottom__: nil }
type kid_doubled_ret = untyped
type source_aliased_ret = { __bottom__: nil }
type source_catch_value_ret = { __bottom__: nil }
type source_defined_dyn_ret = { __bottom__: nil }
type source_enum_value_ret = { __bottom__: nil }
type source_ewo_param_ret = untyped
type source_for_var_ret = { __bottom__: nil }
type source_ident2_ret = { __bottom__: nil }
type source_ident3_ret = { __bottom__: nil }
type source_ident4_ret = { __bottom__: nil }
type source_ident_ret = { __bottom__: nil }
type source_initialize_ret = Hash[String, Integer]
type source_inject_acc_ret = untyped
type source_ivar_get_ret = { __bottom__: nil }
type source_ivar_reflective_len_ret = { __bottom__: nil }
type source_ivar_reflective_ret = { __bottom__: nil }
type source_loop_break_len_ret = { __bottom__: nil }
type source_loop_break_ret = { __bottom__: nil }
type source_method_missing_ret = { __bottom__: nil }
type source_named_capture_len_ret = { __bottom__: nil }
type source_named_capture_ret = { __bottom__: nil }
type source_slice_param_ret = { __bottom__: nil }
type source_via_missing_len_ret = { __bottom__: nil }
type source_via_missing_ret = { __bottom__: nil }
type source_zip_param_ret = { __bottom__: nil }
