type trees_controller_canonical_arg0 = Integer | String | Hash[Integer | String | Hash[String | untyped, String | untyped] | untyped, Integer | String | Hash[Integer | String | Hash[String | untyped, String | untyped] | untyped, Integer | String | Hash[String | untyped, String | untyped] | untyped] | untyped | untyped]
type trees_controller_canonical_ret = Integer | String | Hash[Integer | String | Hash[String | untyped, String | untyped], Integer | String | Hash[String | untyped, String | untyped]]
