type trees_controller_canonical_arg0 = Hash[String, Integer | Hash[String | untyped, Integer | String | untyped]]
type trees_controller_canonical_ret = Hash[String | untyped, Integer | String | untyped]
