type base_doubled_ret = untyped
type kid_doubled_ret = untyped
type source_aliased_ret = untyped
type source_catch_value_ret = untyped
type source_defined_dyn_ret = untyped
type source_enum_value_ret = untyped
type source_ewo_param_ret = untyped
type source_for_var_ret = untyped
type source_ident2_ret = untyped
type source_ident3_ret = untyped
type source_ident4_ret = untyped
type source_ident_ret = untyped
type source_initialize_ret = Hash[String, Integer]
type source_inject_acc_ret = untyped
type source_ivar_get_ret = untyped
type source_ivar_reflective_len_ret = Integer
type source_ivar_reflective_ret = untyped
type source_loop_break_len_ret = Integer
type source_loop_break_ret = untyped
type source_method_missing_ret = untyped
type source_named_capture_len_ret = Integer
type source_named_capture_ret = untyped
type source_slice_param_ret = untyped
type source_via_missing_len_ret = Integer
type source_via_missing_ret = untyped
type source_zip_param_ret = untyped
